export { carregarAtletica } from './carregar-atletica'
export { comAlfa, corTextoSobre } from './cores'
export { paleta } from './paleta'
export { ProvedorTema } from './provedor-tema'
export { useAtletica, useConsultaAtletica, type Atletica } from './use-atletica'
